version: '3'

services:
  tasks_service:
    build:
      context: ./tasks
    ports:
      - "5001:5001"

  users_service:
    build:
      context: ./users
    ports:
      - "5002:5002"

  webapp:
    build:
      context: ./web
    ports:
      - "5000:5000"
    depends_on:
      - tasks_service
      - users_service